abstract class SocialState{}

class intialSocialState extends SocialState{}
class LoadingSocialState extends SocialState{}
class SuccessSocialState extends SocialState{}
class ErrorSocialState extends SocialState{}
class BottomNavChangeState extends SocialState{}
class AddPostState extends SocialState{}
class UpdateProfilePhotoSuccess extends SocialState{}
class UpdateProfilePhotoError extends SocialState{}
class UpdateCoverPhotoSuccess extends SocialState{}
class UpdateCoverPhotoError extends SocialState{}
class UpdateUserError extends SocialState{}
class UpdateUserLoading extends SocialState{}
class UpdateProfileLoading extends SocialState{}
class UpdateCoverLoading extends SocialState{}
class CreatePostLoading extends SocialState{}
class CreatePostSuccess extends SocialState{}
class CreatePostError extends SocialState{}
class UpdatePostPhotoError extends SocialState{}
class UpdatePostPhotoSuccess extends SocialState{}
class RemovePostPhoto extends SocialState{}
class GetPostSuccess extends SocialState{}
class GetePostError extends SocialState{}
class GetPostLoading extends SocialState{}
class LikesSuccess extends SocialState{}
class LikesError extends SocialState{}
class GetLikesSuccess extends SocialState{}
class GetLikesError extends SocialState{}
class CommentSuccess extends SocialState{}
class CommentError extends SocialState{}
class GetCommentError extends SocialState{}
class GetCommentLoading extends SocialState{}
class GetLikeLoading extends SocialState{}
class GetCommentSuccess extends SocialState{}
class GetAllUsersSuccess extends SocialState{}
class GetAllUsersLoading extends SocialState{}
class GetAllUsersError extends SocialState{}
class SendMessageSuccess extends SocialState{}
class SendMessageError extends SocialState{}
class GetMessageSuccess extends SocialState{}
class GetMessageError extends SocialState{}
class GetImageMessageSuccess extends SocialState{}
class GetImageMessageError extends SocialState{}
class RemoveSendImage extends SocialState{}
class SignoutSuccess extends SocialState{}
class SignoutError extends SocialState{}
class deleteUsersSuccess extends SocialState{}

